AllCops:
  TargetRubyVersion: 2.2
Metrics/LineLength:
  Max: 128
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Style/ConstantName:
  Enabled: false
# blocked on https://github.com/appium/ruby_lib/issues/312. Already removed from core part
Style/GlobalVars:
  Enabled: false
Style/AccessorMethodName:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/EachWithObject:
  Enabled: false
Style/SpaceAroundOperators:
  Enabled: false
Style/ExtraSpacing:
  Enabled: false
Style/IndentHash:
  Enabled: false
Style/VariableNumber:
  EnforcedStyle: 'snake_case'
Style/MultilineOperationIndentation:
  Enabled: false
Lint/NestedMethodDefinition:
  Enabled: false
# Should enable and fix for Ruby3
Style/FrozenStringLiteralComment:
  Enabled: false
# Can use over Ruby2.3
Style/SafeNavigation:
  Enabled: false
# Can use over Ruby2.3
Style/NumericPredicate:
  Enabled: false
