AllCops:
  TargetRubyVersion: 2.3
Metrics/LineLength:
  Max: 128
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
# blocked on https://github.com/appium/ruby_lib/issues/312. Already removed from core part
Style/GlobalVars:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
# Can use over Ruby2.3
Style/SafeNavigation:
  Enabled: false
# Can use over Ruby2.3
Style/NumericPredicate:
  Enabled: false
Style/CommentedKeyword:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false
Layout/IndentHeredoc:
  Enabled: false
Layout/RescueEnsureAlignment:
  Enabled: false
