# Custom config for RuboCop static code analysis
Metrics/LineLength:
  Max: 125
Metrics/MethodLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Style/ConstantName:
  Enabled: false
# blocked on https://github.com/appium/ruby_lib/issues/312
Style/GlobalVars:
  Enabled: false
Style/AccessorMethodName:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/EachWithObject:
  Enabled: false
